### ISSUE TITLE
Release 1.0 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#1]
- [x] features complete
- [x] Testing complete
- [x] apps submitted to stores
- [x ] app released in apple app store
- [x] app released in google play store
- [ ] make app available as sample in AppStudio
- [x] move repo to public facing github/Esri
- [x] add to labs.esri.com
- [x] make marketplace listing available
- [x] geonet blog released
