### ISSUE TITLE
Release 3.1 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#106]
- [x] features complete
- [x] Testing complete
- [x] apps **submitted** to stores
    - [x] Windows store
    - [x] Apple store
    - [x] Google play store
- [x] app **released** in stores
    - [x] Windows store MSIX
    - [x] Apple store
    - [x] Google play store
- [x] windows desktop app available via public appcenter page
- [x] make app update available as sample in AppStudio (new online item for appstudio 5.0 only)
- [x] update release notes wiki - https://github.com/Esri/Trek2There/wiki/Release-Notes
- [x] update marketplace listing - https://marketplace.arcgis.com/listing.html?id=a1a3caec68694eaf8b6e0c25f0657275
- [x] geonet blog released
#

**Comment by brettstokes** [comment]
MSIX files have been created for v3.1.19 and are available in AppCenter:
- [Signed](https://install.appcenter.ms/orgs/appstudio-h0at/apps/Trek2There_x86_Signed.msix)
- [Unsigned](https://install.appcenter.ms/orgs/appstudio-h0at/apps/Trek2There_x86_UnSigned.msix)

**Comment by phil-wilson** [comment]
@marikavertzonis @anshuman-mathur @brettstokes Trek2There was rejected from Microsoft Store with following reason:

> Please take the following action
> 
> We reviewed your submission and identified some changes that are needed before we can publish or update the app. Please make these changes and resubmit your app. For more information, contact reportapp@microsoft.com Please include your app ID so we can act quickly.
> 
> App Policies: 10.1.1 Inaccurate Representation - Icon
> 
> Notes To Developer
> 
> There is an issue with the functionality of the product. An additional installed component of the product visible in the Start Menu does not work as expected.
> 
> Content Policies: 11.10 Region Specific Requirements - Sensitive Content
> 
> Notes To Developer
> 
> The app contains references to content not allowed in China including mentioning Taiwan, China by an unauthorized name (Taiwan or the Republic of China or ROC). Please resubmit your app with those mentions corrected to Taiwan, China.
> Here’s where we found the content (but please also remove similar content throughout the app and metadata):
> In-app > Map
> 
> Please Note
> Your current certification results might differ from earlier submissions because Microsoft Store policy requirements can change over time. When policies change, we might re-test according to the new requirements regardless of the submission type. Please always rely on your most recent certification results.
> General Resources
> Microsoft Store Policies
> Application Developer Agreement (ADA)
> Developer Code of Conduct

**Comment by dominikargast** [comment]
@phil-wilson @marikavertzonis @anshuman-mathur @brettstokes Regarding the first point, the way I'm reading this is that we install another app together with T2T. Could it be an uninstaller that does not work correctly? (I don't have a windows machine at the moment with which I could test this.)

The reference to Taiwan seems to be the fact that Taiwan labeled on the map as such (instead of Taiwan, China?). If this is the case, we will have a problem on our hands with any app that displays a map. Can we push back on that at all? There is no mention of Taiwan or China or ROC in the app itself.

**Comment by marikavertzonis** [comment]
- this page is the explanation of each warning - https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies
- regarding icon issue - it infers an unexpected icon is deployed to start menu - we previously had an icon clean up problem on windows - need to test on a clean machine
- regarding the map issue - agreed this is something we inherit. options might be to remove the map page (brute force approach and wont help us elsewhere), change the basemap to the World Imagery (has no labels), or change the default basemap and add basemap switcher (still might mean a tester will find the map with labels...)

**Comment by dominikargast** [comment]
@marikavertzonis I'm not sure how useful the world imagery map is. If we show that then we should probably also add a basemap switcher and we potentially run into the same issue.

Disabling the map can simply done by setting a switch to false. If our main concern is getting T2T out the door then this is probably the quickest way to resolve this issue.
