### ISSUE TITLE
Release 1.1 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#58]
- [x] features complete
- [x] Testing complete
- [x] apps submitted to stores
- [x] app released in apple app store
- [x] app released in google play store
- [x] windows app available via public hockey app page
- [x] make app update available as sample in AppStudio
- [x] update marketplace listing 
- [ ] geonet blog released
