### ISSUE TITLE
Release 2.0 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#62]
- [x] features complete
- [x] Testing complete
- [x] apps submitted to stores
- [x] app released in apple app store
- [x] app released in google play store
- [x] windows app available via public hockey app page
- [x] make app update available as sample in AppStudio
- [x] update release notes wiki
- [x] update marketplace listing 
- [x] geonet blog released
