### ISSUE TITLE
Release 3.0 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#94]
- [ ] features complete
- [ ] Testing complete
- [ ] apps **submitted** to stores
       - [ ] windows uwp
       - [ ] apple store
       - [ ] google play store
- [ ] app **released** in stores
       - [ ] windows uwp
       - [ ] apple store
       - [ ] google play store
- [ ] windows desktop app available via public hockey app page
- [ ] make app update available as sample in AppStudio
- [ ] update release notes wiki - https://github.com/Esri/Trek2There/wiki/Release-Notes
- [ ] update marketplace listing - https://marketplace.arcgis.com/listing.html?id=a1a3caec68694eaf8b6e0c25f0657275
- [ ] geonet blog released - draft is here https://esri.app.box.com/notes/297590706900

**Comment by IsmaelInRedlands** [comment]
@JohnHasthorpe  We also support USNG.  Pretty important for Search and Rescue teams. http://napsg.maps.arcgis.com/apps/MapSeries/index.html?appid=4914d6e6e47041e098c093701ff2e50e

**Comment by IsmaelInRedlands** [comment]
[T2T.docx](https://github.com/Esri/Trek2There/files/2130544/T2T.docx)
Attaching blog draft from Marika

**Comment by IsmaelInRedlands** [comment]
Blog post to be posted here: https://community.esri.com/community/esri-labs

**Comment by JohnHasthorpe** [comment]
@IsmaelInRedlands - Thanks, very helpful. 
What's new updated based on doc. USNG added.

**Comment by marikavertzonis** [comment]
Oh gosh so sorry about box link,  I musn't have shared it.  I just tried and I can't log into box on my phone cause I don't have the authentication set up.
From memory,  your list looks good.
I also think this will the last emails I get,  I'm getting mail box full messages.
Yasou

**Comment by JohnHasthorpe** [comment]
@marikavertzonis Just to summarise where we are:
- The released version for iOS, Android and Windows was 3.0.36 (builds are currently suspended)
- The version given to Rex was 3.0.37 (as some changes were required for UWP store readiness). This is not in the store yet.

We will update the store versions with 3.0.37 post-UC as we don't want to delay things now.

- I have emailed Alan C about the Marketplace update

**Comment by marikavertzonis** [comment]
- marketplace listing has been updated
- the windows link in the marketplace currently goes to hockeyapp - was pointing to version 1.0.55, now points to version 3.0.36
- windows store item is live 
    - https://www.microsoft.com/en-au/p/trek2there/9n9nlvh74l5k?activetab=pivot%3Aoverviewtab
    - i successfully installed from store on windows 10 desktop and windows 10 phone

**Comment by marikavertzonis** [comment]
followed up email to Alan C about adding the link to the Windows Store to marketplace listing
